package com.budgetplusplus.database

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import kotlin.system.measureTimeMillis
import org.junit.*
import org.junit.Assert.*
import org.junit.runner.RunWith
import org.robolectric.RobolectricTestRunner
import org.robolectric.annotation.Config

@RunWith(RobolectricTestRunner::class) @Config(sdk=[35])
class PerformanceScaleTest {
 @Test fun `search and aggregation remain bounded at 10k 50k and 100k operations`(){val db=Room.inMemoryDatabaseBuilder(ApplicationProvider.getApplicationContext<Context>(),BudgetPlusDatabase::class.java).allowMainThreadQueries().build();val sql=db.openHelper.writableDatabase;createSearchInfrastructure(sql);sql.execSQL("INSERT INTO workspaces VALUES ('w','Scale','PERSONAL','DZD',1,1,1,NULL)");sql.execSQL("INSERT INTO accounts VALUES ('a','w','Cash','CASH','DZD',0,'primary','account','',0,0,0,1,1,NULL,NULL)");sql.execSQL("INSERT INTO categories VALUES ('c','w','EXPENSE',NULL,'Food','category','primary',0,0,0,1,1,NULL)");val insert=sql.compileStatement("INSERT INTO finance_transactions(id,workspace_id,type,amount_minor,currency_code,account_id,category_id,occurred_at,local_date,zone_id,description,note,merchant,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)");val milestones=mutableMapOf<Int,Long>();val elapsed=measureTimeMillis{sql.beginTransaction();try{for(i in 1..100_000){insert.clearBindings();insert.bindString(1,"tx-$i");insert.bindString(2,"w");insert.bindString(3,if(i%5==0)"INCOME" else "EXPENSE");insert.bindLong(4,(i%10_000+1).toLong());insert.bindString(5,"DZD");insert.bindString(6,"a");insert.bindString(7,"c");insert.bindLong(8,i.toLong());insert.bindString(9,"2026-${((i%12)+1).toString().padStart(2,'0')}-${((i%28)+1).toString().padStart(2,'0')}");insert.bindString(10,"Africa/Algiers");insert.bindString(11,"merchant batch ${i%100}");insert.bindString(12,"");insert.bindString(13,"");insert.bindLong(14,i.toLong());insert.bindLong(15,i.toLong());insert.executeInsert();if(i==10_000||i==50_000||i==100_000)milestones[i]=System.nanoTime()};sql.setTransactionSuccessful()}finally{sql.endTransaction()}};assertEquals(setOf(10_000,50_000,100_000),milestones.keys);assertTrue("100k insertion exceeded safety budget: ${elapsed}ms",elapsed<180_000);val queryTime=measureTimeMillis{sql.query("SELECT id FROM finance_transactions WHERE deleted_at IS NULL ORDER BY occurred_at DESC,id DESC LIMIT 51").use{assertEquals(51,it.count)};sql.query("SELECT transaction_id FROM finance_transactions_fts WHERE description MATCH '\"merchant\"*' LIMIT 51").use{assertEquals(51,it.count)};sql.query("SELECT SUM(amount_minor) FROM finance_transactions WHERE deleted_at IS NULL AND local_date BETWEEN '2026-01-01' AND '2026-12-31'").use{assertTrue(it.moveToFirst())}};assertTrue("indexed queries exceeded safety budget: ${queryTime}ms",queryTime<5_000);val plan=sql.query("EXPLAIN QUERY PLAN SELECT id FROM finance_transactions WHERE deleted_at IS NULL ORDER BY occurred_at DESC,id DESC LIMIT 51").use{cursor->buildString{while(cursor.moveToNext())append(cursor.getString(3))}};assertTrue(plan.contains("index_finance_transactions_deleted_at_occurred_at_id"));db.close()}
}
