package com.budgetplusplus.database.entity

import androidx.room.*
import com.budgetplusplus.core.model.FavoriteBehavior

@Entity(tableName="media_assets",indices=[Index("deleted_at")])
data class MediaAssetEntity(@PrimaryKey val id:String,@ColumnInfo(name="file_name")val fileName:String,@ColumnInfo(name="thumbnail_file_name")val thumbnailFileName:String,val width:Int,val height:Int,@ColumnInfo(name="size_bytes")val sizeBytes:Long,@ColumnInfo(name="created_at")val createdAt:Long,@ColumnInfo(name="deleted_at")val deletedAt:Long?=null)

@Entity(tableName="favorites",foreignKeys=[ForeignKey(entity=WorkspaceEntity::class,parentColumns=["id"],childColumns=["workspace_id"],onDelete=ForeignKey.CASCADE),ForeignKey(entity=MediaAssetEntity::class,parentColumns=["id"],childColumns=["media_id"],onDelete=ForeignKey.SET_NULL),ForeignKey(entity=AccountEntity::class,parentColumns=["id"],childColumns=["account_id"],onDelete=ForeignKey.RESTRICT),ForeignKey(entity=CategoryEntity::class,parentColumns=["id"],childColumns=["category_id"],onDelete=ForeignKey.RESTRICT),ForeignKey(entity=SubcategoryEntity::class,parentColumns=["id"],childColumns=["subcategory_id"],onDelete=ForeignKey.SET_NULL)],indices=[Index("workspace_id","is_archived","display_order"),Index("media_id"),Index("account_id"),Index("category_id"),Index("subcategory_id")])
data class FavoriteEntity(@PrimaryKey val id:String,@ColumnInfo(name="workspace_id")val workspaceId:String,val name:String,@ColumnInfo(name="media_id")val mediaId:String?=null,@ColumnInfo(name="icon_key")val iconKey:String,@ColumnInfo(name="color_key")val colorKey:String,@ColumnInfo(name="unit_price_minor")val unitPriceMinor:Long,@ColumnInfo(name="currency_code")val currencyCode:String,@ColumnInfo(name="account_id")val accountId:String,@ColumnInfo(name="category_id")val categoryId:String,@ColumnInfo(name="subcategory_id")val subcategoryId:String?=null,val description:String,val behavior:FavoriteBehavior,@ColumnInfo(name="display_order")val displayOrder:Int=0,@ColumnInfo(name="is_archived")val isArchived:Boolean=false,@ColumnInfo(name="created_at")val createdAt:Long,@ColumnInfo(name="updated_at")val updatedAt:Long,@ColumnInfo(name="deleted_at")val deletedAt:Long?=null)

@Entity(tableName="favorite_click_batches",foreignKeys=[ForeignKey(entity=FavoriteEntity::class,parentColumns=["id"],childColumns=["favorite_id"],onDelete=ForeignKey.CASCADE),ForeignKey(entity=FinanceTransactionEntity::class,parentColumns=["id"],childColumns=["transaction_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("transaction_id")])
data class FavoriteClickBatchEntity(@PrimaryKey @ColumnInfo(name="favorite_id")val favoriteId:String,@ColumnInfo(name="transaction_id")val transactionId:String,@ColumnInfo(name="last_clicked_at")val lastClickedAt:Long,val quantity:Int)
