package com.budgetplusplus.database.entity

import androidx.room.*
import com.budgetplusplus.core.model.DuePriority

@Entity(tableName="future_payments",foreignKeys=[ForeignKey(entity=WorkspaceEntity::class,parentColumns=["id"],childColumns=["workspace_id"],onDelete=ForeignKey.CASCADE),ForeignKey(entity=CategoryEntity::class,parentColumns=["id"],childColumns=["category_id"],onDelete=ForeignKey.RESTRICT),ForeignKey(entity=SubcategoryEntity::class,parentColumns=["id"],childColumns=["subcategory_id"],onDelete=ForeignKey.SET_NULL),ForeignKey(entity=AccountEntity::class,parentColumns=["id"],childColumns=["planned_account_id"],onDelete=ForeignKey.SET_NULL)],indices=[Index("workspace_id","due_date","cancelled","deleted_at"),Index("category_id"),Index("subcategory_id"),Index("planned_account_id"),Index("priority","due_date")])
data class FuturePaymentEntity(@PrimaryKey val id:String,@ColumnInfo(name="workspace_id")val workspaceId:String,val name:String,val description:String,@ColumnInfo(name="planned_amount_minor")val plannedAmountMinor:Long,@ColumnInfo(name="currency_code")val currencyCode:String,@ColumnInfo(name="due_date")val dueDate:String,@ColumnInfo(name="category_id")val categoryId:String,@ColumnInfo(name="subcategory_id")val subcategoryId:String?=null,@ColumnInfo(name="planned_account_id")val plannedAccountId:String?=null,val priority:DuePriority,@ColumnInfo(name="reminder_enabled")val reminderEnabled:Boolean,@ColumnInfo(name="reminder_days_before")val reminderDaysBefore:Int,val notes:String,val cancelled:Boolean=false,@ColumnInfo(name="created_at")val createdAt:Long,@ColumnInfo(name="updated_at")val updatedAt:Long,@ColumnInfo(name="deleted_at")val deletedAt:Long?=null)

@Entity(tableName="due_payments",foreignKeys=[ForeignKey(entity=FuturePaymentEntity::class,parentColumns=["id"],childColumns=["due_id"],onDelete=ForeignKey.CASCADE),ForeignKey(entity=FinanceTransactionEntity::class,parentColumns=["id"],childColumns=["transaction_id"],onDelete=ForeignKey.RESTRICT)],indices=[Index("due_id","cancelled_at"),Index(value=["transaction_id"],unique=true)])
data class DuePaymentEntity(@PrimaryKey val id:String,@ColumnInfo(name="due_id")val dueId:String,@ColumnInfo(name="transaction_id")val transactionId:String,@ColumnInfo(name="amount_minor")val amountMinor:Long,@ColumnInfo(name="paid_date")val paidDate:String,@ColumnInfo(name="created_at")val createdAt:Long,@ColumnInfo(name="cancelled_at")val cancelledAt:Long?=null)

@Entity(tableName="due_reminder_events",primaryKeys=["due_id","reminder_date"],foreignKeys=[ForeignKey(entity=FuturePaymentEntity::class,parentColumns=["id"],childColumns=["due_id"],onDelete=ForeignKey.CASCADE)],indices=[Index("due_id")])
data class DueReminderEventEntity(@ColumnInfo(name="due_id")val dueId:String,@ColumnInfo(name="reminder_date")val reminderDate:String,@ColumnInfo(name="notified_at")val notifiedAt:Long)
