package com.budgetplusplus.feature.recurring

import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewModelScope
import com.budgetplusplus.core.designsystem.components.*
import com.budgetplusplus.core.designsystem.financial.MoneyText
import com.budgetplusplus.core.model.*
import com.budgetplusplus.domain.repository.*
import dagger.hilt.android.lifecycle.HiltViewModel
import java.time.LocalDate
import java.time.ZoneId
import javax.inject.Inject
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch

@HiltViewModel class RecurringViewModel @Inject constructor(private val repository:RecurringRepository,accounts:AccountRepository,categoryRepository:CategoryRepository):ViewModel(){
 val rules=repository.observeRecurring().stateIn(viewModelScope,SharingStarted.WhileSubscribed(5000),emptyList());val history=repository.observeOccurrences().stateIn(viewModelScope,SharingStarted.WhileSubscribed(5000),emptyList());val accounts=accounts.observeAccounts().map{it.filterNot(Account::isArchived)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5000),emptyList());val categories=categoryRepository.observeCategories().map{it.filterNot(Category::isArchived)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5000),emptyList());val subs=categoryRepository.observeSubcategories().map{it.filterNot(Subcategory::isArchived)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5000),emptyList());private val _error=MutableStateFlow(false);val error=_error.asStateFlow()
 private fun action(block:suspend()->Unit,done:()->Unit={})=viewModelScope.launch{runCatching{block()}.onSuccess{_error.value=false;done()}.onFailure{_error.value=true}}
 fun save(v:RecurringInput,done:()->Unit)=action({repository.save(v)},done);fun active(v:RecurringTransaction)=action({repository.setActive(v.id,!v.isActive)});fun delete(v:RecurringTransaction,done:()->Unit)=action({repository.delete(v.id)},done);fun clear(){_error.value=false}
}

@Composable fun RecurringScreen(onBack:(()->Unit)?,vm:RecurringViewModel=hiltViewModel()){
 val rules by vm.rules.collectAsStateWithLifecycle();val history by vm.history.collectAsStateWithLifecycle();val accounts by vm.accounts.collectAsStateWithLifecycle();val categories by vm.categories.collectAsStateWithLifecycle();val subs by vm.subs.collectAsStateWithLifecycle();val error by vm.error.collectAsStateWithLifecycle();var showHistory by remember{mutableStateOf(false)};var create by remember{mutableStateOf(false)};var edit by remember{mutableStateOf<RecurringTransaction?>(null)};var remove by remember{mutableStateOf<RecurringTransaction?>(null)};val snack=remember{SnackbarHostState()};val message=stringResource(R.string.recurring_error);LaunchedEffect(error){if(error){snack.showSnackbar(message);vm.clear()}}
 Scaffold(snackbarHost={SnackbarHost(snack)},topBar={BudgetTopAppBar(stringResource(R.string.recurring_title),onBackClick=onBack)},floatingActionButton={if(!showHistory)FloatingActionButton({create=true}){Text(stringResource(R.string.recurring_add))}}){p->Column(Modifier.padding(p).fillMaxSize()){Row(Modifier.padding(16.dp),horizontalArrangement=Arrangement.spacedBy(8.dp)){FilterChip(!showHistory,{showHistory=false},{Text(stringResource(R.string.recurring_rules))});FilterChip(showHistory,{showHistory=true},{Text(stringResource(R.string.recurring_history))})}
  if(showHistory){if(history.isEmpty())BudgetEmptyState(stringResource(R.string.recurring_no_history),stringResource(R.string.recurring_no_history_message),Modifier.fillMaxSize())else LazyColumn{items(history,key={it.id}){o->ListItem(headlineContent={Text(o.dueDate)},supportingContent={Text(stringResource(if(o.status==RecurrenceOccurrenceStatus.CREATED)R.string.recurring_created else R.string.recurring_failed))});HorizontalDivider()}}}
  else if(rules.isEmpty())BudgetEmptyState(stringResource(R.string.recurring_empty),stringResource(R.string.recurring_empty_message),Modifier.fillMaxSize(),actionText=stringResource(R.string.recurring_create),onAction={create=true})
  else LazyColumn(contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){items(rules,key={it.id}){r->ElevatedCard{Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(r.name,style=MaterialTheme.typography.titleMedium);AssistChip({}, {Text(stringResource(if(r.isActive)R.string.recurring_active else R.string.recurring_paused))})};MoneyText(r.amountMinor,r.currencyCode);Text(stringResource(R.string.recurring_next,r.nextDueDate));Text(frequencyLabel(r.frequency));Row{TextButton({vm.active(r)}){Text(stringResource(if(r.isActive)R.string.recurring_pause else R.string.recurring_activate))};TextButton({edit=r}){Text(stringResource(R.string.recurring_edit))};TextButton({remove=r}){Text(stringResource(R.string.recurring_delete))}}}}}}
 }}
 if(create)Editor(null,accounts,categories,subs,{create=false}){vm.save(it){create=false}};edit?.let{r->Editor(r,accounts,categories,subs,{edit=null}){vm.save(it){edit=null}}};remove?.let{r->BudgetConfirmationDialog(stringResource(R.string.recurring_delete_title),stringResource(R.string.recurring_delete_message,r.name),{vm.delete(r){remove=null}},{remove=null},confirmText=stringResource(R.string.recurring_delete),destructive=true)}
}

@Composable private fun Editor(old:RecurringTransaction?,accounts:List<Account>,categories:List<Category>,subs:List<Subcategory>,dismiss:()->Unit,save:(RecurringInput)->Unit){var name by remember{mutableStateOf(old?.name.orEmpty())};var type by remember{mutableStateOf(old?.type?:TransactionType.EXPENSE)};var amount by remember{mutableStateOf(old?.amountMinor?.let{format(it)}.orEmpty())};var account by remember{mutableStateOf(old?.accountId?:accounts.firstOrNull()?.id.orEmpty())};var destination by remember{mutableStateOf(old?.destinationAccountId)};var category by remember{mutableStateOf(old?.categoryId)};var sub by remember{mutableStateOf(old?.subcategoryId)};var frequency by remember{mutableStateOf(old?.frequency?:RecurrenceFrequency.MONTHLY)};var start by remember{mutableStateOf(old?.startDate?:LocalDate.now().toString())};var end by remember{mutableStateOf(old?.endDate.orEmpty())};var description by remember{mutableStateOf(old?.description.orEmpty())};val parsed=parse(amount);val valid=name.isNotBlank()&&parsed!=null&&parsed>0&&account.isNotBlank()&&runCatching{LocalDate.parse(start)}.isSuccess&&(end.isBlank()||runCatching{LocalDate.parse(end)}.isSuccess)&&(if(type==TransactionType.TRANSFER)destination!=null&&destination!=account else category!=null)
 AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(if(old==null)R.string.recurring_new else R.string.recurring_edit_title))},text={LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){item{BudgetTextField(name,{name=it},stringResource(R.string.recurring_name))};item{Row{TransactionType.entries.forEach{v->FilterChip(type==v,{type=v;category=null;destination=null},{Text(typeLabel(v))},Modifier.padding(end=4.dp))}}};item{com.budgetplusplus.core.designsystem.components.BudgetAmountField(amount,{amount=it},stringResource(R.string.recurring_amount),stringResource(R.string.recurring_currency))};item{Select(stringResource(R.string.recurring_account),accounts,account,{it.id},{it.name}){account=it.id}};if(type==TransactionType.TRANSFER)item{Select(stringResource(R.string.recurring_destination),accounts.filter{it.id!=account},destination,{it.id},{it.name}){destination=it.id}}else item{val eligible=categories.filter{it.kind.name==type.name};Select(stringResource(R.string.recurring_category),eligible,category,{it.id},{catName(it)}){category=it.id;sub=null};val child=subs.filter{it.categoryId==category};if(child.isNotEmpty())Select(stringResource(R.string.recurring_subcategory),child,sub,{it.id},{it.name}){sub=it.id}};item{Row{RecurrenceFrequency.entries.forEach{v->FilterChip(frequency==v,{frequency=v},{Text(frequencyLabel(v))},Modifier.padding(end=4.dp))}}};item{BudgetTextField(start,{start=it},stringResource(R.string.recurring_start),supportingText=stringResource(R.string.recurring_date_hint))};item{BudgetTextField(end,{end=it},stringResource(R.string.recurring_end),supportingText=stringResource(R.string.recurring_optional))};item{BudgetTextField(description,{description=it},stringResource(R.string.recurring_description))}}},confirmButton={TextButton({save(RecurringInput(old?.id,name.trim(),type,parsed!!,account,destination,category,sub,description,frequency,start,end.ifBlank{null},ZoneId.systemDefault().id))},enabled=valid){Text(stringResource(R.string.recurring_save))}},dismissButton={TextButton(dismiss){Text(stringResource(R.string.recurring_cancel))}})
}
@Composable private fun <T> Select(label:String,values:List<T>,selected:String?,id:(T)->String,text: @Composable (T) -> String,choose:(T)->Unit){var open by remember{mutableStateOf(false)};val current=values.firstOrNull{id(it)==selected};Box{OutlinedButton({open=true},Modifier.fillMaxWidth()){Text(current?.let{text(it)}?:label)};DropdownMenu(open,{open=false}){values.forEach{v->DropdownMenuItem({Text(text(v))},{choose(v);open=false})}}}}
@Composable private fun typeLabel(v:TransactionType)=stringResource(when(v){TransactionType.EXPENSE->R.string.recurring_expense;TransactionType.INCOME->R.string.recurring_income;TransactionType.TRANSFER->R.string.recurring_transfer})
@Composable private fun frequencyLabel(v:RecurrenceFrequency)=stringResource(when(v){RecurrenceFrequency.DAILY->R.string.recurring_daily;RecurrenceFrequency.WEEKLY->R.string.recurring_weekly;RecurrenceFrequency.MONTHLY->R.string.recurring_monthly;RecurrenceFrequency.YEARLY->R.string.recurring_yearly})
@Composable private fun catName(v:Category)=v.customName?:stringResource(R.string.recurring_system_category)
private fun format(v:Long)="${v/100}.${(v%100).toString().padStart(2,'0')}";internal fun parse(v:String):Long?{val p=v.replace(',','.').split('.');if(p.size>2||p.any{x->x.any{!it.isDigit()}})return null;val a=p[0].ifBlank{"0"}.toLongOrNull()?:return null;val b=p.getOrNull(1).orEmpty();if(b.length>2)return null;return runCatching{Math.addExact(Math.multiplyExact(a,100),b.padEnd(2,'0').ifBlank{"0"}.toLong())}.getOrNull()}
