package com.budgetplusplus.feature.futurepayments

import android.Manifest
import android.os.Build
import androidx.activity.compose.rememberLauncherForActivityResult
import androidx.activity.result.contract.ActivityResultContracts
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Modifier
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewModelScope
import com.budgetplusplus.core.designsystem.components.*
import com.budgetplusplus.core.designsystem.financial.*
import com.budgetplusplus.core.model.*
import com.budgetplusplus.domain.repository.*
import dagger.hilt.android.lifecycle.HiltViewModel
import java.time.LocalDate
import java.util.UUID
import javax.inject.Inject
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch

@HiltViewModel class FuturePaymentsViewModel @Inject constructor(private val repository:FuturePaymentRepository,accountsRepository:AccountRepository,categoriesRepository:CategoryRepository):ViewModel(){val dues=repository.observeFuturePayments().stateIn(viewModelScope,SharingStarted.WhileSubscribed(5000),emptyList());val accounts=accountsRepository.observeAccounts().map{it.filterNot(Account::isArchived)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5000),emptyList());val categories=categoriesRepository.observeCategories(CategoryKind.EXPENSE).map{it.filterNot(Category::isArchived)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5000),emptyList());val subcategories=categoriesRepository.observeSubcategories().map{it.filterNot(Subcategory::isArchived)}.stateIn(viewModelScope,SharingStarted.WhileSubscribed(5000),emptyList());private val _error=MutableStateFlow(false);val error=_error.asStateFlow()
 private fun action(block:suspend()->Unit,done:()->Unit={})=viewModelScope.launch{runCatching{block()}.onSuccess{done()}.onFailure{_error.value=true}}
 fun save(input:FuturePaymentInput,done:()->Unit)=action({repository.save(input)},done);fun cancelDue(value:FuturePayment)=action({repository.setCancelled(value.id,!value.cancelled)});fun pay(due:FuturePayment,request:String,account:String,amount:Long,date:String,done:()->Unit)=action({repository.pay(due.id,request,account,amount,date)},done);fun cancelPayment(id:String)=action({repository.cancelPayment(id)});fun payments(id:String)=repository.observePayments(id);fun clearError(){_error.value=false}}

@Composable fun FuturePaymentsScreen(onBack:()->Unit,vm:FuturePaymentsViewModel=hiltViewModel()){val dues by vm.dues.collectAsStateWithLifecycle();val accounts by vm.accounts.collectAsStateWithLifecycle();val categories by vm.categories.collectAsStateWithLifecycle();val subs by vm.subcategories.collectAsStateWithLifecycle();val error by vm.error.collectAsStateWithLifecycle();var edit by remember{mutableStateOf<FuturePayment?>(null)};var create by remember{mutableStateOf(false)};var pay by remember{mutableStateOf<FuturePayment?>(null)};var history by remember{mutableStateOf<FuturePayment?>(null)};var status by remember{mutableStateOf<DueStatus?>(null)};var priority by remember{mutableStateOf<DuePriority?>(null)};var accountFilter by remember{mutableStateOf<String?>(null)};var categoryFilter by remember{mutableStateOf<String?>(null)};var from by remember{mutableStateOf<String?>(null)};var to by remember{mutableStateOf<String?>(null)};val snackbar=remember{SnackbarHostState()};val errorText=stringResource(R.string.dues_error);LaunchedEffect(error){if(error){snackbar.showSnackbar(errorText);vm.clearError()}};val permission=rememberLauncherForActivityResult(ActivityResultContracts.RequestPermission()){};val visible=dues.filter{(status==null||it.status==status)&&(priority==null||it.priority==priority)&&(accountFilter==null||it.plannedAccountId==accountFilter)&&(categoryFilter==null||it.categoryId==categoryFilter)&&(from==null||it.dueDate>=from!!)&&(to==null||it.dueDate<=to!!)};val upcoming=dues.count{it.status==DueStatus.UPCOMING||it.status==DueStatus.TODAY};val overdue=dues.count{it.status==DueStatus.OVERDUE};val remaining=dues.filter{it.status !in setOf(DueStatus.PAID,DueStatus.CANCELLED)}.fold(0L){total,due->Math.addExact(total,due.remainingMinor.coerceAtLeast(0))}
 Scaffold(snackbarHost={SnackbarHost(snackbar)},topBar={BudgetTopAppBar(stringResource(R.string.dues_title),onBackClick=onBack)},floatingActionButton={FloatingActionButton({create=true}){Text(stringResource(R.string.dues_add))}}){p->LazyColumn(Modifier.padding(p).fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){item{Summary(upcoming,overdue,remaining)};item{LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){item{FilterChip(status==null,{status=null},{Text(stringResource(R.string.dues_all))})};items(DueStatus.entries){value->FilterChip(status==value,{status=value},{Text(statusLabel(value))})}}};item{LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){item{FilterChip(priority==null,{priority=null},{Text(stringResource(R.string.dues_all_priorities))})};items(DuePriority.entries){value->FilterChip(priority==value,{priority=value},{Text(priorityLabel(value))})}}};item{DueSelector(stringResource(R.string.dues_account_filter),accounts,accountFilter,{it.id},{it.name}){accountFilter=it?.id};DueSelector(stringResource(R.string.dues_category_filter),categories,categoryFilter,{it.id},{categoryName(it)}){categoryFilter=it?.id}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){BudgetTextField(from.orEmpty(),{from=it.ifBlank{null}},stringResource(R.string.dues_from),Modifier.weight(1f));BudgetTextField(to.orEmpty(),{to=it.ifBlank{null}},stringResource(R.string.dues_to),Modifier.weight(1f))}};if(Build.VERSION.SDK_INT>=33)item{TextButton({permission.launch(Manifest.permission.POST_NOTIFICATIONS)}){Text(stringResource(R.string.dues_allow_notifications))}};if(visible.isEmpty())item{BudgetEmptyState(stringResource(R.string.dues_empty),stringResource(R.string.dues_empty_message))}else items(visible,key={it.id}){due->DueCard(due,{pay=due},{history=due},{edit=due},{vm.cancelDue(due)})}}}
 if(create)DueEditor(null,accounts,categories,subs,{create=false}){vm.save(it){create=false}};edit?.let{value->DueEditor(value,accounts,categories,subs,{edit=null}){vm.save(it){edit=null}}};pay?.let{value->PaymentDialog(value,accounts,{pay=null}){request,account,amount,date->vm.pay(value,request,account,amount,date){pay=null}}};history?.let{value->PaymentHistoryDialog(value,vm,{history=null})}
}
@Composable private fun Summary(upcoming:Int,overdue:Int,remaining:Long){ElevatedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Text(stringResource(R.string.dues_summary),style=MaterialTheme.typography.titleMedium);Text(stringResource(R.string.dues_upcoming_count,upcoming));Text(stringResource(R.string.dues_overdue_count,overdue));Text(stringResource(R.string.dues_total_remaining));MoneyText(remaining,"DZD")}}}
@Composable private fun DueCard(value:FuturePayment,pay:()->Unit,history:()->Unit,edit:()->Unit,cancel:()->Unit){ElevatedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(6.dp)){Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(value.name,style=MaterialTheme.typography.titleMedium);AssistChip({}, {Text(statusLabel(value.status))})};Text(stringResource(R.string.dues_due_date,value.dueDate));MoneyText(value.remainingMinor.coerceAtLeast(0),value.currencyCode);LinearProgressIndicator({if(value.plannedAmountMinor<=0)0f else(value.paidAmountMinor.toFloat()/value.plannedAmountMinor.toFloat()).coerceIn(0f,1f)},Modifier.fillMaxWidth());LazyRow(horizontalArrangement=Arrangement.spacedBy(4.dp)){if(value.status !in setOf(DueStatus.PAID,DueStatus.CANCELLED))item{Button(pay){Text(stringResource(R.string.dues_pay))}};item{TextButton(history){Text(stringResource(R.string.dues_payments))}};item{TextButton(edit){Text(stringResource(R.string.dues_edit))}};item{TextButton(cancel){Text(stringResource(if(value.cancelled)R.string.dues_restore else R.string.dues_cancel_due))}}}}}}
@Composable private fun DueEditor(old:FuturePayment?,accounts:List<Account>,categories:List<Category>,subs:List<Subcategory>,dismiss:()->Unit,save:(FuturePaymentInput)->Unit){var name by remember{mutableStateOf(old?.name.orEmpty())};var description by remember{mutableStateOf(old?.description.orEmpty())};var amount by remember{mutableStateOf(old?.plannedAmountMinor?.let(::formatAmount).orEmpty())};var date by remember{mutableStateOf(old?.dueDate?:LocalDate.now().plusDays(1).toString())};var category by remember{mutableStateOf(old?.categoryId)};var sub by remember{mutableStateOf(old?.subcategoryId)};var account by remember{mutableStateOf(old?.plannedAccountId)};var priority by remember{mutableStateOf(old?.priority?:DuePriority.NORMAL)};var reminder by remember{mutableStateOf(old?.reminderEnabled?:false)};var days by remember{mutableStateOf((old?.reminderDaysBefore?:1).toString())};var notes by remember{mutableStateOf(old?.notes.orEmpty())};val parsed=parseAmount(amount);val valid=name.isNotBlank()&&parsed!=null&&parsed>0&&category!=null&&runCatching{LocalDate.parse(date)}.isSuccess&&days.toIntOrNull()?.let { it in 0..365 } == true
 AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(if(old==null)R.string.dues_new else R.string.dues_edit_title))},text={LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){item{BudgetTextField(name,{name=it},stringResource(R.string.dues_name))};item{BudgetTextField(description,{description=it},stringResource(R.string.dues_description))};item{BudgetAmountField(amount,{amount=it},stringResource(R.string.dues_amount),stringResource(R.string.dues_currency))};item{BudgetTextField(date,{date=it},stringResource(R.string.dues_date),supportingText=stringResource(R.string.dues_date_help))};item{DueSelector(stringResource(R.string.dues_category),categories,category,{it.id},{categoryName(it)}){category=it?.id;sub=null}};val children=subs.filter{it.categoryId==category};if(children.isNotEmpty())item{DueSelector(stringResource(R.string.dues_subcategory),children,sub,{it.id},{it.name}){sub=it?.id}};item{DueSelector(stringResource(R.string.dues_planned_account),accounts,account,{it.id},{it.name}){account=it?.id}};item{LazyRow{items(DuePriority.entries){value->FilterChip(priority==value,{priority=value},{Text(priorityLabel(value))},Modifier.padding(end=4.dp))}}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Text(stringResource(R.string.dues_reminder));Switch(reminder,{reminder=it})}};if(reminder)item{BudgetTextField(days,{days=it.filter(Char::isDigit)},stringResource(R.string.dues_reminder_days))};item{BudgetTextField(notes,{notes=it},stringResource(R.string.dues_notes),singleLine=false)}}},confirmButton={TextButton({save(FuturePaymentInput(old?.id,name.trim(),description.trim(),parsed!!,"DZD",date,requireNotNull(category),sub,account,priority,reminder,days.toIntOrNull()?:1,notes.trim()))},enabled=valid){Text(stringResource(R.string.dues_save))}},dismissButton={TextButton(dismiss){Text(stringResource(R.string.dues_close))}})}
@Composable private fun PaymentDialog(value:FuturePayment,accounts:List<Account>,dismiss:()->Unit,pay:(String,String,Long,String)->Unit){val request=remember{UUID.randomUUID().toString()};var account by remember{mutableStateOf(value.plannedAccountId?:accounts.firstOrNull()?.id)};var amount by remember{mutableStateOf(formatAmount(value.remainingMinor.coerceAtLeast(0)))};var date by remember{mutableStateOf(LocalDate.now().toString())};var confirm by remember{mutableStateOf(false)};val parsed=parseAmount(amount);val valid=account!=null&&parsed!=null&&parsed>0&&parsed<=value.remainingMinor&&runCatching{LocalDate.parse(date)}.isSuccess;AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(R.string.dues_pay_title))},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){DueSelector(stringResource(R.string.dues_actual_account),accounts,account,{it.id},{it.name}){account=it?.id};BudgetAmountField(amount,{amount=it},stringResource(R.string.dues_payment_amount),value.currencyCode);BudgetTextField(date,{date=it},stringResource(R.string.dues_payment_date))}},confirmButton={TextButton({confirm=true},enabled=valid){Text(stringResource(R.string.dues_pay))}},dismissButton={TextButton(dismiss){Text(stringResource(R.string.dues_close))}});if(confirm)BudgetConfirmationDialog(stringResource(R.string.dues_payment_confirm_title),stringResource(R.string.dues_payment_confirm_message,amount,value.name),{confirm=false;pay(request,requireNotNull(account),requireNotNull(parsed),date)},{confirm=false},confirmText=stringResource(R.string.dues_pay))}
@Composable private fun PaymentHistoryDialog(value:FuturePayment,vm:FuturePaymentsViewModel,dismiss:()->Unit){
 val payments by vm.payments(value.id).collectAsStateWithLifecycle(emptyList());var pending by remember{mutableStateOf<DuePayment?>(null)}
 AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(R.string.dues_payments))},text={if(payments.isEmpty())Text(stringResource(R.string.dues_no_payments))else LazyColumn{items(payments,key={it.id}){payment->ListItem(headlineContent={MoneyText(payment.amountMinor,"DZD")},supportingContent={Text(stringResource(R.string.dues_payment_line,payment.paidDate,payment.accountName))},trailingContent={if(!payment.cancelled)TextButton({pending=payment}){Text(stringResource(R.string.dues_cancel_payment))}})}}},confirmButton={TextButton(dismiss){Text(stringResource(R.string.dues_close))}})
 pending?.let{payment->BudgetConfirmationDialog(stringResource(R.string.dues_cancel_payment_title),stringResource(R.string.dues_cancel_payment_message),{vm.cancelPayment(payment.id);pending=null},{pending=null},confirmText=stringResource(R.string.dues_cancel_payment),destructive=true)}
}
@Composable private fun <T> DueSelector(label:String,values:List<T>,selected:String?,id:(T)->String,text: @Composable (T) -> String,choose:(T?)->Unit){var open by remember{mutableStateOf(false)};val current=values.firstOrNull{id(it)==selected};Box{OutlinedButton({open=true},Modifier.fillMaxWidth()){Text(current?.let{text(it)}?:label)};DropdownMenu(open,{open=false}){DropdownMenuItem({Text(stringResource(R.string.dues_none))},{choose(null);open=false});values.forEach{value->DropdownMenuItem({Text(text(value))},{choose(value);open=false})}}}}
@Composable private fun statusLabel(value:DueStatus)=stringResource(when(value){DueStatus.UPCOMING->R.string.dues_status_upcoming;DueStatus.TODAY->R.string.dues_status_today;DueStatus.OVERDUE->R.string.dues_status_overdue;DueStatus.PARTIALLY_PAID->R.string.dues_status_partial;DueStatus.PAID->R.string.dues_status_paid;DueStatus.CANCELLED->R.string.dues_status_cancelled})
@Composable private fun priorityLabel(value:DuePriority)=stringResource(when(value){DuePriority.LOW->R.string.dues_priority_low;DuePriority.NORMAL->R.string.dues_priority_normal;DuePriority.HIGH->R.string.dues_priority_high;DuePriority.URGENT->R.string.dues_priority_urgent})
@Composable private fun categoryName(value:Category)=value.customName?:stringResource(R.string.dues_system_category)
private fun formatAmount(value:Long)="${value/100}.${(value%100).toString().padStart(2,'0')}"
internal fun parseAmount(value:String):Long?{val parts=value.trim().replace(',','.').split('.');if(parts.size>2||parts.any{p->p.any{!it.isDigit()}})return null;val major=parts[0].ifEmpty{"0"}.toLongOrNull()?:return null;val minor=parts.getOrNull(1).orEmpty();if(minor.length>2)return null;return runCatching{Math.addExact(Math.multiplyExact(major,100),minor.padEnd(2,'0').ifEmpty{"0"}.toLong())}.getOrNull()}
