package com.budgetplusplus.feature.accounts

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.lazy.*
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.stringResource
import androidx.compose.ui.semantics.contentDescription
import androidx.compose.ui.semantics.semantics
import androidx.compose.ui.unit.dp
import androidx.hilt.navigation.compose.hiltViewModel
import androidx.lifecycle.ViewModel
import androidx.lifecycle.compose.collectAsStateWithLifecycle
import androidx.lifecycle.viewModelScope
import com.budgetplusplus.core.designsystem.components.*
import com.budgetplusplus.core.designsystem.financial.*
import com.budgetplusplus.core.designsystem.icons.BudgetIcons
import com.budgetplusplus.core.model.*
import com.budgetplusplus.domain.repository.*
import com.budgetplusplus.domain.accounts.AccountHierarchy
import dagger.hilt.android.lifecycle.HiltViewModel
import java.text.DateFormat
import java.util.Date
import javax.inject.Inject
import kotlinx.coroutines.Job
import kotlinx.coroutines.flow.*
import kotlinx.coroutines.launch

@HiltViewModel class AccountDetailViewModel @Inject constructor(private val accountsRepository:AccountRepository,private val searchRepository:SearchRepository):ViewModel(){
 val accounts=accountsRepository.observeAccounts().stateIn(viewModelScope,SharingStarted.WhileSubscribed(5000),emptyList());private val _totals=MutableStateFlow(AccountOperationTotals());val totals=_totals.asStateFlow();private val _metrics=MutableStateFlow(AccountHierarchyMetrics());val metrics=_metrics.asStateFlow();private val _rows=MutableStateFlow<List<FinanceTransaction>>(emptyList());val rows=_rows.asStateFlow();private val _loading=MutableStateFlow(false);val loading=_loading.asStateFlow();private val _error=MutableStateFlow(false);val error=_error.asStateFlow();private val _selected=MutableStateFlow<Set<String>>(emptySet());val selected=_selected.asStateFlow();private var accountId:String="";private var cursor:SearchCursor?=null;private var end=false;private var totalsJob:Job?=null;private var metricsJob:Job?=null;var query by mutableStateOf("");var type by mutableStateOf<TransactionType?>(null);var sort by mutableStateOf(TransactionSort.DATE_DESC);var fromDate by mutableStateOf<String?>(null);var toDate by mutableStateOf<String?>(null)
 fun load(id:String){if(accountId==id)return;accountId=id;totalsJob?.cancel();totalsJob=viewModelScope.launch{accountsRepository.observeTotals(id).collect{_totals.value=it}};metricsJob?.cancel();metricsJob=viewModelScope.launch{accountsRepository.observeHierarchyMetrics(id).collect{_metrics.value=it}};apply()}
 fun apply(){cursor=null;end=false;_rows.value=emptyList();loadMore()}
 fun loadMore(){if(_loading.value||end||accountId.isBlank())return;_loading.value=true;viewModelScope.launch{runCatching{searchRepository.search(TransactionSearchFilter(query,type,accountId,fromDate=fromDate,toDate=toDate,sort=sort),cursor)}.onSuccess{page->_rows.value=(_rows.value+page.items).takeLast(1000);cursor=page.nextCursor;end=page.nextCursor==null}.onFailure{_error.value=true};_loading.value=false}}
 fun toggle(id:String){_selected.value=if(id in _selected.value)_selected.value-id else _selected.value+id}
 fun clearSelection(){_selected.value=emptySet()}
 fun update(account:Account,name:String,type:AccountType,icon:String,color:String,description:String,order:Int,done:()->Unit)=viewModelScope.launch{runCatching{accountsRepository.update(account.id,name,type,icon,color,description,order)}.onSuccess{done()}.onFailure{_error.value=true}}
 fun moveAccount(account:Account,parentId:String?,done:()->Unit)=viewModelScope.launch{runCatching{accountsRepository.move(account.id,parentId)}.onSuccess{done()}.onFailure{_error.value=true}}
 fun archive(account:Account,done:()->Unit)=viewModelScope.launch{runCatching{accountsRepository.setArchived(account.id,!account.isArchived)}.onSuccess{done()}.onFailure{_error.value=true}}
 fun reassign(target:String,done:()->Unit)=viewModelScope.launch{runCatching{accountsRepository.reassignOperations(accountId,target,_selected.value)}.onSuccess{clearSelection();apply();done()}.onFailure{_error.value=true}}
 fun delete(target:String?,done:()->Unit)=viewModelScope.launch{runCatching{accountsRepository.deleteAndReassign(accountId,target)}.onSuccess{done()}.onFailure{_error.value=true}}
 fun clearError(){_error.value=false}
}

@Composable fun AccountDetailScreen(accountId:String,onBack:()->Unit,onEditTransaction:(String)->Unit,onQuickAdd:(TransactionType,String)->Unit,onNavigateAccount:(String)->Unit,vm:AccountDetailViewModel=hiltViewModel()){val accounts by vm.accounts.collectAsStateWithLifecycle();val totals by vm.totals.collectAsStateWithLifecycle();val metrics by vm.metrics.collectAsStateWithLifecycle();val rows by vm.rows.collectAsStateWithLifecycle();val loading by vm.loading.collectAsStateWithLifecycle();val error by vm.error.collectAsStateWithLifecycle();val selected by vm.selected.collectAsStateWithLifecycle();val account=accounts.firstOrNull{it.id==accountId};val breadcrumb=AccountHierarchy.breadcrumb(accountId,accounts);val children=accounts.filter{it.parentAccountId==accountId};val descendantIds=AccountHierarchy.descendantIds(accountId,accounts);var edit by remember{mutableStateOf(false)};var archive by remember{mutableStateOf(false)};var delete by remember{mutableStateOf(false)};var move by remember{mutableStateOf(false)};var moveAccount by remember{mutableStateOf(false)};val snack=remember{SnackbarHostState()};val errorText=stringResource(R.string.account_detail_error);LaunchedEffect(accountId){vm.load(accountId)};LaunchedEffect(error){if(error){snack.showSnackbar(errorText);vm.clearError()}}
 Scaffold(snackbarHost={SnackbarHost(snack)},topBar={BudgetTopAppBar(account?.name?:stringResource(R.string.account_detail_title),onBackClick=onBack,onMoreClick={edit=true})}){p->if(account==null)BudgetLoadingIndicator(Modifier.padding(p).fillMaxSize())else LazyColumn(Modifier.padding(p).fillMaxSize(),contentPadding=PaddingValues(16.dp),verticalArrangement=Arrangement.spacedBy(10.dp)){
  item{if(breadcrumb.size>1)LazyRow(horizontalArrangement=Arrangement.spacedBy(4.dp)){items(breadcrumb,key={it.id}){entry->TextButton({onNavigateAccount(entry.id)}){Text(entry.name)}}}};item{AccountHeader(account,metrics)};if(children.isNotEmpty())item{Column{Text(stringResource(R.string.account_detail_children),style=MaterialTheme.typography.titleMedium);LazyRow{items(children,key={it.id}){child->AssistChip({onNavigateAccount(child.id)},{Text(child.name)},Modifier.padding(end=6.dp))}}}};item{LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){items(TransactionType.entries){type->Button({onQuickAdd(type,account.id)}){Text(quickLabel(type))}}}};item{BudgetSearchBar(vm.query,{vm.query=it},placeholder=stringResource(R.string.account_detail_search))};item{LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){item{FilterChip(vm.type==null,{vm.type=null;vm.apply()},{Text(stringResource(R.string.account_detail_all))})};items(TransactionType.entries){type->FilterChip(vm.type==type,{vm.type=type;vm.apply()},{Text(typeLabel(type))})}}};item{Row(horizontalArrangement=Arrangement.spacedBy(8.dp)){BudgetTextField(vm.fromDate.orEmpty(),{vm.fromDate=it.ifBlank{null}},stringResource(R.string.account_detail_from),Modifier.weight(1f));BudgetTextField(vm.toDate.orEmpty(),{vm.toDate=it.ifBlank{null}},stringResource(R.string.account_detail_to),Modifier.weight(1f))}};item{LazyRow(horizontalArrangement=Arrangement.spacedBy(6.dp)){items(TransactionSort.entries){sort->FilterChip(vm.sort==sort,{vm.sort=sort;vm.apply()},{Text(sortLabel(sort))})}}};item{Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Button(vm::apply){Text(stringResource(R.string.account_detail_apply))};if(selected.isNotEmpty())Button({move=true}){Text(stringResource(R.string.account_detail_move_count,selected.size))}}};if(rows.isEmpty()&&!loading)item{BudgetEmptyState(stringResource(R.string.account_detail_empty),stringResource(R.string.account_detail_empty_message))}else items(rows,key={it.id}){transaction->Row(verticalAlignment=Alignment.CenterVertically){Checkbox(transaction.id in selected,{vm.toggle(transaction.id)});Box(Modifier.weight(1f)){AccountTransactionRow(transaction,onEditTransaction)}}};if(loading)item{BudgetLoadingIndicator(Modifier.fillMaxWidth())}else if(rows.isNotEmpty())item{LaunchedEffect(rows.size){vm.loadMore()}}
  item{HorizontalDivider();LazyRow(horizontalArrangement=Arrangement.spacedBy(8.dp)){item{OutlinedButton({edit=true}){Text(stringResource(R.string.account_detail_edit_account))}};item{OutlinedButton({moveAccount=true}){Text(stringResource(R.string.account_detail_move_account))}};item{OutlinedButton({archive=true}){Text(stringResource(if(account.isArchived)R.string.accounts_restore else R.string.accounts_archive))}};item{TextButton({delete=true}){Text(stringResource(R.string.account_detail_delete))}}}}
 }}
 if(edit&&account!=null)AccountEditorDialog(account,{edit=false}){name,type,icon,color,description,order->vm.update(account,name,type,icon,color,description,order){edit=false}}
 if(archive&&account!=null)BudgetConfirmationDialog(stringResource(if(account.isArchived)R.string.accounts_restore_title else R.string.accounts_archive_title),stringResource(if(account.isArchived)R.string.accounts_restore_message else R.string.accounts_archive_message,account.name),{vm.archive(account){archive=false}},{archive=false},confirmText=stringResource(if(account.isArchived)R.string.accounts_restore else R.string.accounts_archive))
 if(moveAccount&&account!=null)MoveAccountDialog(account,accounts.filter{it.id!=account.id&&it.id !in descendantIds&&!it.isArchived},{moveAccount=false}){parent->vm.moveAccount(account,parent){moveAccount=false}}
 if(move&&account!=null)ReassignDialog(account,accounts.filter{it.id!=account.id&&!it.isArchived},selected.size,{move=false}){target->vm.reassign(target){move=false}}
 if(delete&&account!=null)DeleteAccountDialog(account,totals,metrics.descendantCount,accounts.filter{it.id!=account.id&&it.id !in descendantIds&&!it.isArchived},{delete=false},{archive=false;delete=false;vm.archive(account,onBack)}){target->vm.delete(target,onBack)}
}

@Composable private fun AccountHeader(account:Account,metrics:AccountHierarchyMetrics){ElevatedCard(Modifier.fillMaxWidth()){Column(Modifier.padding(16.dp),verticalArrangement=Arrangement.spacedBy(8.dp)){Row(verticalAlignment=Alignment.CenterVertically,horizontalArrangement=Arrangement.spacedBy(12.dp)){Box(Modifier.size(48.dp).background(accountColor(account.colorKey),CircleShape),contentAlignment=Alignment.Center){Icon(accountIcon(account.iconKey),contentDescription=stringResource(R.string.account_detail_icon),tint=Color.White)};Column{Text(account.name,style=MaterialTheme.typography.titleLarge);if(account.description.isNotBlank())Text(account.description)}};Text(stringResource(R.string.account_detail_own_balance));MoneyText(metrics.ownBalanceMinor,account.currencyCode);Text(stringResource(R.string.account_detail_consolidated_balance));MoneyText(metrics.consolidatedBalanceMinor,account.currencyCode);Row(Modifier.fillMaxWidth(),horizontalArrangement=Arrangement.SpaceBetween){Column{Text(stringResource(R.string.account_detail_own_income));MoneyText(metrics.ownIncomeMinor,account.currencyCode,tone=AmountTone.Income);Text(stringResource(R.string.account_detail_consolidated_income));MoneyText(metrics.consolidatedIncomeMinor,account.currencyCode,tone=AmountTone.Income)};Column{Text(stringResource(R.string.account_detail_own_expenses));MoneyText(-metrics.ownExpenseMinor,account.currencyCode,tone=AmountTone.Expense);Text(stringResource(R.string.account_detail_consolidated_expenses));MoneyText(-metrics.consolidatedExpenseMinor,account.currencyCode,tone=AmountTone.Expense)}};Text(stringResource(R.string.account_detail_descendant_count,metrics.descendantCount),style=MaterialTheme.typography.labelMedium)}}}
@Composable private fun AccountTransactionRow(value:FinanceTransaction,edit:(String)->Unit){TransactionRow(value.categoryCustomName?:stringResource(R.string.account_detail_transaction),value.description,DateFormat.getDateInstance(DateFormat.MEDIUM).format(Date(value.occurredAt)),value.accountName,value.amountMinor,value.currencyCode,when(value.type){TransactionType.EXPENSE->TransactionVisualType.Expense;TransactionType.INCOME->TransactionVisualType.Income;TransactionType.TRANSFER->TransactionVisualType.Transfer},BudgetIcons.Category,onClick={edit(value.id)})}
@Composable private fun AccountEditorDialog(value:Account,dismiss:()->Unit,save:(String,AccountType,String,String,String,Int)->Unit){var name by remember{mutableStateOf(value.name)};var type by remember{mutableStateOf(value.type)};var icon by remember{mutableStateOf(value.iconKey)};var color by remember{mutableStateOf(value.colorKey)};var description by remember{mutableStateOf(value.description)};var order by remember{mutableStateOf(value.displayOrder.toString())};AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(R.string.account_detail_edit_account))},text={LazyColumn(verticalArrangement=Arrangement.spacedBy(8.dp)){item{BudgetTextField(name,{name=it},stringResource(R.string.accounts_name))};item{LazyRow{items(AccountType.entries){candidate->FilterChip(type==candidate,{type=candidate},{Text(accountType(candidate))},Modifier.padding(end=4.dp))}}};item{LazyRow{items(listOf("account","home","search")){candidate->FilterChip(icon==candidate,{icon=candidate},{Icon(accountIcon(candidate),contentDescription=iconLabel(candidate))},Modifier.padding(end=4.dp))}}};item{LazyRow{items(listOf("primary","green","orange","blue")){candidate->val label=colorLabel(candidate);FilterChip(color==candidate,{color=candidate},{Box(Modifier.size(24.dp).background(accountColor(candidate),CircleShape).semantics{contentDescription=label})},Modifier.padding(end=4.dp))}}};item{BudgetTextField(description,{if(it.length<=120)description=it},stringResource(R.string.account_detail_description))};item{BudgetTextField(order,{order=it.filter(Char::isDigit)},stringResource(R.string.account_detail_order))}}},confirmButton={TextButton({save(name.trim(),type,icon,color,description,order.toIntOrNull()?:0)},enabled=name.isNotBlank()&&order.toIntOrNull()!=null){Text(stringResource(R.string.account_detail_save))}},dismissButton={TextButton(dismiss){Text(stringResource(R.string.account_detail_cancel))}})}
@Composable private fun MoveAccountDialog(account:Account,targets:List<Account>,dismiss:()->Unit,confirm:(String?)->Unit){var parent by remember{mutableStateOf(account.parentAccountId)};AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(R.string.account_detail_move_account))},text={Column(verticalArrangement=Arrangement.spacedBy(6.dp)){FilterChip(parent==null,{parent=null},{Text(stringResource(R.string.accounts_main_account))});targets.forEach{target->FilterChip(parent==target.id,{parent=target.id},{Text(target.name)})}}},confirmButton={TextButton({confirm(parent)}){Text(stringResource(R.string.account_detail_move_confirm))}},dismissButton={TextButton(dismiss){Text(stringResource(R.string.account_detail_cancel))}})}
@Composable private fun ReassignDialog(source:Account,targets:List<Account>,count:Int,dismiss:()->Unit,confirm:(String)->Unit){var target by remember{mutableStateOf<String?>(null)};AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(R.string.account_detail_move_title))},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text(stringResource(R.string.account_detail_move_message,count,source.name));targets.forEach{account->FilterChip(target==account.id,{target=account.id},{Text(account.name)})}}},confirmButton={TextButton({confirm(requireNotNull(target))},enabled=target!=null){Text(stringResource(R.string.account_detail_move_confirm))}},dismissButton={TextButton(dismiss){Text(stringResource(R.string.account_detail_cancel))}})}
@Composable private fun DeleteAccountDialog(account:Account,totals:AccountOperationTotals,descendantCount:Int,targets:List<Account>,dismiss:()->Unit,archive:()->Unit,delete:(String?)->Unit){var target by remember{mutableStateOf<String?>(null)};val used=totals.operationCount>0||descendantCount>0;AlertDialog(onDismissRequest=dismiss,title={Text(stringResource(R.string.account_detail_delete_title))},text={Column(verticalArrangement=Arrangement.spacedBy(8.dp)){Text(if(descendantCount>0)stringResource(R.string.account_detail_delete_descendants,descendantCount)else stringResource(if(used)R.string.account_detail_delete_used else R.string.account_detail_delete_empty,totals.operationCount));if(used){Text(stringResource(R.string.account_detail_choose_replacement));targets.forEach{candidate->FilterChip(target==candidate.id,{target=candidate.id},{Text(candidate.name)})}}}},confirmButton={Column{if(used)TextButton(archive){Text(stringResource(R.string.account_detail_archive_instead))};TextButton({delete(target)},enabled=!used||target!=null){Text(stringResource(R.string.account_detail_reassign_delete),color=MaterialTheme.colorScheme.error)}}},dismissButton={TextButton(dismiss){Text(stringResource(R.string.account_detail_cancel))}})}
@Composable private fun quickLabel(type:TransactionType)=stringResource(when(type){TransactionType.EXPENSE->R.string.account_detail_add_expense;TransactionType.INCOME->R.string.account_detail_add_income;TransactionType.TRANSFER->R.string.account_detail_add_transfer})
@Composable private fun typeLabel(type:TransactionType)=stringResource(when(type){TransactionType.EXPENSE->R.string.account_detail_expense;TransactionType.INCOME->R.string.account_detail_income_type;TransactionType.TRANSFER->R.string.account_detail_transfer})
@Composable private fun sortLabel(sort:TransactionSort)=stringResource(when(sort){TransactionSort.DATE_DESC->R.string.account_detail_date_desc;TransactionSort.DATE_ASC->R.string.account_detail_date_asc;TransactionSort.AMOUNT_DESC->R.string.account_detail_amount_desc;TransactionSort.AMOUNT_ASC->R.string.account_detail_amount_asc})
@Composable private fun accountType(type:AccountType)=stringResource(when(type){AccountType.CASH->R.string.account_type_cash;AccountType.BANK->R.string.account_type_bank;AccountType.SAVINGS->R.string.account_type_savings;AccountType.CARD->R.string.account_type_card;AccountType.OTHER->R.string.account_type_other})
private fun accountIcon(key:String)=when(key){"home"->BudgetIcons.Home;"search"->BudgetIcons.Search;else->BudgetIcons.Account}
private fun accountColor(key:String)=when(key){"green"->Color(0xFF2E7D32);"orange"->Color(0xFFEF6C00);"blue"->Color(0xFF1565C0);else->Color(0xFF386A54)}
@Composable private fun iconLabel(key:String)=stringResource(when(key){"home"->R.string.account_detail_icon_home;"search"->R.string.account_detail_icon_search;else->R.string.account_detail_icon_account})
@Composable private fun colorLabel(key:String)=stringResource(when(key){"green"->R.string.account_detail_color_green;"orange"->R.string.account_detail_color_orange;"blue"->R.string.account_detail_color_blue;else->R.string.account_detail_color_primary})
